codice/thirdparty

ffmpeg/pom.xml
ffmpeg/src/assembly/descriptor.xml
pom.xml

DDF-1823 Add FFmpeg binaries

---

ffmpeg/pom.xml

DDF-1823 Add Solaris binary

---

geotools-suite-8.4/pom.xml

upgrade dependency version to resolve OSAWP findings

DDF-2173 upgrade dependency version to resolve OSAWP findings

---

tika-bundle/pom.xml

DDF-2751 Added parent to tika bundle pom

---

tika-bundle/README.md

@kcwire @jlcsmith 
Added README to maintain the tika-bundle

DDF-2751 Added README

---

tika-bundle/pom.xml

@kcwire 
We will have to redeploy artifacts

DDF-2751 Changed tika-bundle version

---

tika-bundle/pom.xml

@bdeining @shaundmorris Can you guys give this a look? 
Who/what is responsible for deploying the artifacts?

DDF-3054 Update tika version and exclude vulnerable library

---

tika-bundle/pom.xml

@shaundmorris @bdeining Can you guys take a look at this?

DDF-3054 Remove exclusion and update imports

---

tika-bundle/pom.xml

DDF-3442 Removes opennlp from tika-bundle

---

ffmpeg/README.md
ffmpeg/pom.xml

[DDF-3824](https://codice.atlassian.net/browse/DDF-3842)
This PR is responsible for updating the binaries for Linux, MacOS, and Windows. It also adds a README for future updating instructions.
To manually test this, download the correct binary for your OS type
[Linux](https://github.com/bakejeyner/thirdparty/blob/7e8b291680a2ea8181f445d7b40dff7c784fe715/ffmpeg/src/main/resources/linux/ffmpeg)
[Mac](https://github.com/bakejeyner/thirdparty/blob/7e8b291680a2ea8181f445d7b40dff7c784fe715/ffmpeg/src/main/resources/osx/ffmpeg)
[Windows](https://github.com/bakejeyner/thirdparty/blob/7e8b291680a2ea8181f445d7b40dff7c784fe715/ffmpeg/src/main/resources/windows/ffmpeg.exe)
Then, run this command in the same directory as the binary
```
./ffmpeg -i <MPG_FILE> -vf thumbnail,scale=200:-1 -frames:v 1 …
```

DDF-3842 Upgrade included ffmpeg binaries

---

geotools-suite/pom.xml

What does this PR do?
Adds Shapefile support to geotools-suite
Who is reviewing it?
Please choose AT LEAST four reviewers.
@bdeining 
@Schachte 
@Bdthomson 
@GabrielFabian 
At least one reviewer should be a code owner.
How should this be tested? Justify why only a full build is sufficient for testing.
Build Thirdparty
Full Build DDF
Full Build Alliance
Any background context you want to provide?
What are the relevant tickets?
DDF-4022

DDF-4022 Add gt-shapefile to geotools-suite

---

Jenkinsfile

This will allow the thirdparty project to be built and deployed at a regular interval.
@LinkMJB @bdeining @brjeter @jrnorth @shaundmorris

Add Jenkinsfile to the thirdparty project.

---

tika-bundle/pom.xml

Updating the version of the Tika-bundle after the last change so the changes can be deployed
@clockard @coyotesqrl @blen-desta @brjeter @stustison

DDF-4197 Updating the version of tika-bundle to 1.18.0_3

---

javalin/pom.xml
pom.xml

I didn't add versions to the `Import-Package` statements because I can't find any other places where we mix it with a resolution of `optional`.

DDF-4477 Add Javalin third party module

---

tika-bundle/pom.xml

@brendan-hofmann @clockard @figliold

DDF-05012 Exclude bzip dependency from tika

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/thirdparty/40)

Update Travis-CI to build with openJDK8

---

geotools-suite/pom.xml
gt-opengis/pom.xml
jts/pom.xml
tika-bundle/pom.xml

DDF-5817 fixed bundles to all work with geotools 20.1 correctly

---

ffmpeg/README.md
ffmpeg/pom.xml

new binaries for Mac, Linux, and Windows
@codice/build 
@codice/continuous-integration 
@bakejeyner 
@jlcsmith
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/thirdparty/47)

DDF-5809 Upgrade FFmpeg to 4.2.2

---

Jenkinsfile

Upgraded the version of Maven to 'maven-latest' in the Jenkinsfile. 
@shaundmorris 
@LinkMJB 
@bdeining 
@bdeining
@shaundmorris
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/thirdparty_TM/job/master/
BR-42 Upgrade Maven version
https://octoconsulting.atlassian.net/jira/software/projects/BR/boards/47?selectedIssue=BR-42

BR-42 Upgrade Maven version

---

cal10n-api/pom.xml

Also, add a name and remove parent to make it consistent with other thirdparty modules

Fix cal10n-api groupId

---

tika-bundle/pom.xml

Upgrade Apache Tika to 1.26
@kentmorrissey
@shaundmorris
@zta6
@SmithJosh

Upgrade Tika to 1.26
